-- Audit manager writes without copying sensitive row contents into the log.
create table if not exists public.shift_board_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid,
  actor_email text,
  actor_role text,
  actor_site_id text,
  action text not null,
  data_key text not null,
  details jsonb not null default '{}'::jsonb
);
alter table public.shift_board_audit enable row level security;
revoke all on public.shift_board_audit from anon;
grant select on public.shift_board_audit to authenticated;
drop policy if exists "upper management views audit" on public.shift_board_audit;
create policy "upper management views audit" on public.shift_board_audit
for select to authenticated
using ((select auth.jwt()->'app_metadata'->>'role')='super');

create or replace function public.audit_shift_board_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is not null then
    insert into public.shift_board_audit(
      actor_id,actor_email,actor_role,actor_site_id,action,data_key,details
    ) values (
      auth.uid(),lower(coalesce(auth.jwt()->>'email','')),
      coalesce(auth.jwt()->'app_metadata'->>'role',''),coalesce(auth.jwt()->'app_metadata'->>'siteId',''),
      lower(tg_op),coalesce(new.key,old.key),
      jsonb_build_object(
        'oldBytes',case when tg_op='INSERT' then 0 else length(coalesce(old.value,'null'::jsonb)::text) end,
        'newBytes',case when tg_op='DELETE' then 0 else length(coalesce(new.value,'null'::jsonb)::text) end
      )
    );
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end;
$$;
revoke all on function public.audit_shift_board_change() from public,anon,authenticated;
drop trigger if exists shift_board_audit_trigger on public.shift_board;
create trigger shift_board_audit_trigger
after insert or update or delete on public.shift_board
for each row execute function public.audit_shift_board_change();

-- Tony-only daily recovery snapshots, retained for 90 days.
create table if not exists public.shift_board_backups (
  id bigint generated by default as identity primary key,
  taken_at timestamptz not null default now(),
  data jsonb not null
);
alter table public.shift_board_backups enable row level security;
revoke all on public.shift_board_backups from anon;
grant select on public.shift_board_backups to authenticated;
drop policy if exists "Tony views backups" on public.shift_board_backups;
create policy "Tony views backups" on public.shift_board_backups
for select to authenticated
using (lower(coalesce((select auth.jwt()->>'email'),''))='tony@neautoservices.com');

create or replace function public.create_shift_board_backup()
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_id bigint;
begin
  insert into public.shift_board_backups(data)
  select coalesce(jsonb_object_agg(key,value),'{}'::jsonb) from public.shift_board
  returning id into v_id;
  delete from public.shift_board_backups where taken_at < now()-interval '90 days';
  return v_id;
end;
$$;
revoke all on function public.create_shift_board_backup() from public,anon,authenticated;

-- Photos are removed within 15 minutes of the automatic Monday-noon lock,
-- as well as by the existing absolute 30-day limit.
create or replace function public.purge_old_clock_photos()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now_uk timestamp := now() at time zone 'Europe/London';
  v_this_monday timestamp;
  v_locked_cutoff timestamp;
  v_count integer;
begin
  v_this_monday := date_trunc('week',v_now_uk);
  v_locked_cutoff := case when v_now_uk >= v_this_monday+interval '12 hours'
    then v_this_monday else v_this_monday-interval '7 days' end;
  delete from public.clock_photos
  where taken_at < now()-interval '30 days'
     or taken_at < (v_locked_cutoff at time zone 'Europe/London');
  get diagnostics v_count=row_count;
  return v_count;
end;
$$;
revoke all on function public.purge_old_clock_photos() from public,anon,authenticated;

do $$
declare v_job bigint;
begin
  for v_job in select jobid from cron.job where jobname in ('shift-board-photo-cleanup','shift-board-daily-backup') loop
    perform cron.unschedule(v_job);
  end loop;
  perform cron.schedule('shift-board-photo-cleanup','*/15 * * * *','select public.purge_old_clock_photos();');
  perform cron.schedule('shift-board-daily-backup','45 2 * * *','select public.create_shift_board_backup();');
end;
$$;

-- One compact source for the upper-management alert banner.
create or replace function public.manager_operational_alerts()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_role text := coalesce(auth.jwt()->'app_metadata'->>'role','');
  v_alerts jsonb := '[]'::jsonb;
  v_run public.sales_import_runs%rowtype;
  v_stock_date date; v_stock_bad integer; v_targets jsonb; v_missing integer := 0;
begin
  if auth.uid() is null or v_role<>'super' then raise exception 'Upper Management only'; end if;
  select * into v_run from public.sales_import_runs order by run_date desc limit 1;
  if v_run.run_date is null or v_run.run_date < current_date-2 then
    v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('level','error','message','Nightly sales figures have not updated for more than two days.'));
  elsif v_run.status<>'success' then
    v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('level','error','message','Latest sales import is '||v_run.status||coalesce(': '||v_run.message,'')));
  end if;

  select max(snapshot_date) into v_stock_date from public.stock_value_snapshots;
  if v_stock_date is null or v_stock_date < current_date-2 then
    v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('level','warn','message','Stock values have not updated for more than two days.'));
  else
    select count(*) into v_stock_bad from public.stock_value_snapshots
    where snapshot_date=v_stock_date and import_status<>'ok';
    if v_stock_bad>0 then v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object(
      'level','warn','message',v_stock_bad||' stock-value site update'||case when v_stock_bad=1 then '' else 's' end||' need attention.'
    )); end if;
  end if;

  select value into v_targets from public.shift_board where key='targetSheets';
  select count(*) into v_missing
  from jsonb_each(coalesce(v_targets->to_char(current_date,'YYYY-MM')->'sites','{}'::jsonb)) s,
       jsonb_array_elements(coalesce(s.value->'days','[]'::jsonb)) d
  where coalesce((d->>'open')::boolean,false)
    and (d->>'date')::date < current_date
    and coalesce(d->>'actual','')='';
  if v_missing>0 then v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object(
    'level','warn','message',v_missing||' past target-sheet day'||case when v_missing=1 then '' else 's' end||' still need actual sales figures.'
  )); end if;
  return v_alerts;
end;
$$;
revoke all on function public.manager_operational_alerts() from public,anon;
grant execute on function public.manager_operational_alerts() to authenticated;
