-- Tony-managed access to additional private portal tabs, plus private MOT imports.
create table if not exists public.portal_tab_permissions (
  email text not null,
  tab_key text not null check (tab_key in ('stock','analysis','salesvs','mot')),
  granted_by text not null,
  updated_at timestamptz not null default now(),
  primary key (email, tab_key),
  check (email = lower(trim(email)))
);

alter table public.portal_tab_permissions enable row level security;
revoke all on table public.portal_tab_permissions from public, anon;
grant select, insert, update, delete on table public.portal_tab_permissions to authenticated;

drop policy if exists "Users see own additional permissions" on public.portal_tab_permissions;
create policy "Users see own additional permissions"
on public.portal_tab_permissions for select to authenticated
using (
  lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com'
  or email = lower(coalesce((select auth.jwt())->>'email',''))
);

create policy "Tony inserts additional permissions" on public.portal_tab_permissions for insert to authenticated
with check (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com' and lower(granted_by) = 'tony@neautoservices.com');
create policy "Tony updates additional permissions" on public.portal_tab_permissions for update to authenticated
using (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com')
with check (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com' and lower(granted_by) = 'tony@neautoservices.com');
create policy "Tony deletes additional permissions" on public.portal_tab_permissions for delete to authenticated
using (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com');

create or replace function public.has_portal_tab_permission(p_tab text)
returns boolean
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select
    lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com'
    or exists (
      select 1 from public.portal_tab_permissions p
      where p.email = lower(coalesce((select auth.jwt())->>'email',''))
        and p.tab_key = p_tab
    );
$$;

revoke all on function public.has_portal_tab_permission(text) from public, anon;
grant execute on function public.has_portal_tab_permission(text) to authenticated;

create table if not exists public.mot_imports (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('mot_system','autowork')),
  report_month date not null check (report_month = date_trunc('month', report_month)::date),
  file_name text not null,
  row_count integer not null default 0 check (row_count >= 0),
  rows jsonb not null default '[]'::jsonb check (jsonb_typeof(rows) = 'array'),
  uploaded_by text not null,
  uploaded_at timestamptz not null default now(),
  unique (source, report_month)
);

alter table public.mot_imports enable row level security;
revoke all on table public.mot_imports from public, anon;
grant select, insert, update, delete on table public.mot_imports to authenticated;
grant usage, select on sequence public.mot_imports_id_seq to authenticated;

drop policy if exists "Permitted users view MOT imports" on public.mot_imports;
create policy "Permitted users view MOT imports"
on public.mot_imports for select to authenticated
using ((select public.has_portal_tab_permission('mot')));

create policy "Tony inserts MOT imports" on public.mot_imports for insert to authenticated
with check (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com' and lower(uploaded_by) = 'tony@neautoservices.com');
create policy "Tony updates MOT imports" on public.mot_imports for update to authenticated
using (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com')
with check (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com' and lower(uploaded_by) = 'tony@neautoservices.com');
create policy "Tony deletes MOT imports" on public.mot_imports for delete to authenticated
using (lower(coalesce((select auth.jwt())->>'email','')) = 'tony@neautoservices.com');

drop policy if exists "Tony views stock values" on public.stock_value_snapshots;
create policy "Permitted users view stock values"
on public.stock_value_snapshots for select to authenticated
using ((select public.has_portal_tab_permission('stock')));

drop policy if exists "Tony can view site sales analysis" on public.site_sales_analysis_monthly;
create policy "Permitted users view site sales analysis"
on public.site_sales_analysis_monthly for select to authenticated
using (
  (select public.has_portal_tab_permission('analysis'))
  or (select public.has_portal_tab_permission('salesvs'))
);
