create table if not exists public.monthly_hs_checks (
  id uuid primary key default gen_random_uuid(),
  site_id text not null,
  month_start date not null,
  checks jsonb not null default '{}'::jsonb,
  manager_notes text not null default '',
  status text not null default 'draft' check (status in ('draft','published')),
  expected_staff jsonb not null default '[]'::jsonb,
  revision integer not null default 1 check (revision > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  published_by uuid,
  published_by_email text,
  unique(site_id, month_start)
);

create table if not exists public.monthly_hs_acknowledgements (
  id bigint generated by default as identity primary key,
  check_id uuid not null references public.monthly_hs_checks(id) on delete cascade,
  revision integer not null,
  site_id text not null,
  month_start date not null,
  employee_id text not null,
  employee_name text not null,
  acknowledged_at timestamptz not null default now(),
  unique(check_id, revision, employee_id)
);

create index if not exists monthly_hs_checks_month_idx
  on public.monthly_hs_checks(month_start, site_id);
create index if not exists monthly_hs_ack_check_idx
  on public.monthly_hs_acknowledgements(check_id, revision, employee_id);

create or replace function public.monthly_hs_active_staff(p_site_id text)
returns jsonb
language sql
security definer
set search_path=public,pg_temp
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object('id', e->>'id', 'name', e->>'name')
      order by lower(coalesce(e->>'name',''))
    ),
    '[]'::jsonb
  )
  from jsonb_array_elements(
    coalesce((select value->'employees' from public.shift_board where key='config'), '[]'::jsonb)
  ) e
  where coalesce((e->>'active')::boolean, true)
    and coalesce(e->>'siteId','') = coalesce(p_site_id,'')
    and coalesce(e->>'id','') <> '';
$$;

revoke all on function public.monthly_hs_active_staff(text) from public, anon, authenticated;

create or replace function public.stamp_monthly_hs_check()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_role text := coalesce(auth.jwt()->'app_metadata'->>'role','');
  v_site text := coalesce(auth.jwt()->'app_metadata'->>'siteId','');
  v_required text[] := array[
    'grinder','oxy_acetylene','tyre_machine','ramps','brake_rollers','jacks',
    'wheel_balancers','windy_tools','mig_welder','gas_analyser','manual_handling',
    'racking_stacking','step_ladders','housekeeping','ppe','coshh'
  ];
  v_key text;
  v_value text;
  v_content_changed boolean := false;
begin
  if auth.uid() is null or v_role not in ('site','super') then
    raise exception 'Not authorised';
  end if;

  if new.site_id in ('mtslj2e8qsrmk2','mtshgne7zriu4b','mtshovwtlsec4d','mtsojpx7bklqsf') then
    raise exception 'Monthly H&S checks are only used for workshop sites';
  end if;

  if v_role='site' and new.site_id<>v_site then
    raise exception 'Managers can only manage monthly H&S checks for their own site';
  end if;

  new.month_start := date_trunc('month', new.month_start)::date;
  new.updated_at := now();

  if tg_op='UPDATE' and old.status='published' and new.status='draft' then
    raise exception 'Published monthly H&S checks cannot be returned to draft';
  end if;

  if new.status='published' then
    foreach v_key in array v_required loop
      v_value := lower(coalesce(new.checks->v_key->>'status',''));
      if v_value not in ('ok','issue','na') then
        raise exception 'Every monthly H&S item must be marked OK, Issue or N/A before publishing';
      end if;
    end loop;

    if tg_op='INSERT' then
      new.revision := 1;
      v_content_changed := true;
    else
      v_content_changed := old.status <> 'published'
        or old.checks is distinct from new.checks
        or old.manager_notes is distinct from new.manager_notes;
      if old.status='published' and v_content_changed then
        new.revision := old.revision + 1;
      else
        new.revision := old.revision;
      end if;
    end if;

    if tg_op='INSERT' or v_content_changed then
      new.expected_staff := public.monthly_hs_active_staff(new.site_id);
      new.published_at := now();
      new.published_by := auth.uid();
      new.published_by_email := lower(coalesce(auth.jwt()->>'email',''));
    end if;
  end if;

  return new;
end;
$$;

revoke all on function public.stamp_monthly_hs_check() from public, anon, authenticated;

drop trigger if exists monthly_hs_checks_stamp on public.monthly_hs_checks;
create trigger monthly_hs_checks_stamp
before insert or update on public.monthly_hs_checks
for each row execute function public.stamp_monthly_hs_check();

alter table public.monthly_hs_checks enable row level security;
alter table public.monthly_hs_acknowledgements enable row level security;

drop policy if exists monthly_hs_checks_select on public.monthly_hs_checks;
create policy monthly_hs_checks_select on public.monthly_hs_checks
for select to authenticated
using (
  coalesce(auth.jwt()->'app_metadata'->>'role','')='super'
  or (
    coalesce(auth.jwt()->'app_metadata'->>'role','')='site'
    and site_id=coalesce(auth.jwt()->'app_metadata'->>'siteId','')
  )
);

drop policy if exists monthly_hs_checks_insert on public.monthly_hs_checks;
create policy monthly_hs_checks_insert on public.monthly_hs_checks
for insert to authenticated
with check (
  coalesce(auth.jwt()->'app_metadata'->>'role','')='super'
  or (
    coalesce(auth.jwt()->'app_metadata'->>'role','')='site'
    and site_id=coalesce(auth.jwt()->'app_metadata'->>'siteId','')
  )
);

drop policy if exists monthly_hs_checks_update on public.monthly_hs_checks;
create policy monthly_hs_checks_update on public.monthly_hs_checks
for update to authenticated
using (
  coalesce(auth.jwt()->'app_metadata'->>'role','')='super'
  or (
    coalesce(auth.jwt()->'app_metadata'->>'role','')='site'
    and site_id=coalesce(auth.jwt()->'app_metadata'->>'siteId','')
  )
)
with check (
  coalesce(auth.jwt()->'app_metadata'->>'role','')='super'
  or (
    coalesce(auth.jwt()->'app_metadata'->>'role','')='site'
    and site_id=coalesce(auth.jwt()->'app_metadata'->>'siteId','')
  )
);

drop policy if exists monthly_hs_ack_select on public.monthly_hs_acknowledgements;
create policy monthly_hs_ack_select on public.monthly_hs_acknowledgements
for select to authenticated
using (
  coalesce(auth.jwt()->'app_metadata'->>'role','')='super'
  or (
    coalesce(auth.jwt()->'app_metadata'->>'role','')='site'
    and site_id=coalesce(auth.jwt()->'app_metadata'->>'siteId','')
  )
);

revoke all on public.monthly_hs_checks from anon;
revoke all on public.monthly_hs_acknowledgements from anon;
grant select,insert,update on public.monthly_hs_checks to authenticated;
grant select on public.monthly_hs_acknowledgements to authenticated;
grant usage,select on sequence public.monthly_hs_acknowledgements_id_seq to authenticated;

create or replace function public.monthly_hs_kiosk_status(p_site_id text)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_check public.monthly_hs_checks%rowtype;
  v_expected integer := 0;
  v_acked integer := 0;
begin
  select * into v_check
  from public.monthly_hs_checks
  where site_id=p_site_id
    and month_start=date_trunc('month',current_date)::date
    and status='published'
  limit 1;

  if not found then
    return jsonb_build_object('published',false);
  end if;

  v_expected := jsonb_array_length(coalesce(v_check.expected_staff,'[]'::jsonb));
  select count(*)::integer into v_acked
  from public.monthly_hs_acknowledgements a
  where a.check_id=v_check.id and a.revision=v_check.revision;

  return jsonb_build_object(
    'published',true,
    'check_id',v_check.id,
    'month_start',v_check.month_start,
    'revision',v_check.revision,
    'expected_count',v_expected,
    'ack_count',v_acked,
    'outstanding_count',greatest(v_expected-v_acked,0)
  );
end;
$$;

create or replace function public.monthly_hs_for_pin(p_site_id text, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_check public.monthly_hs_checks%rowtype;
  v_emp jsonb;
  v_ack timestamptz;
begin
  if p_pin is null or p_pin !~ '^\d{4}$' then
    return jsonb_build_object('ok',false,'message','PIN not recognised.');
  end if;

  select * into v_check
  from public.monthly_hs_checks
  where site_id=p_site_id
    and month_start=date_trunc('month',current_date)::date
    and status='published'
  limit 1;

  if not found then
    return jsonb_build_object('ok',false,'message','This month''s H&S checks have not been published yet.');
  end if;

  select e into v_emp
  from jsonb_array_elements(
    coalesce((select value->'employees' from public.shift_board where key='config'),'[]'::jsonb)
  ) e
  where coalesce((e->>'active')::boolean,true)
    and coalesce(e->>'siteId','')=p_site_id
    and coalesce(e->>'pin','')=p_pin
  limit 1;

  if v_emp is null then
    return jsonb_build_object('ok',false,'message','PIN not recognised for this site.');
  end if;

  if not exists (
    select 1
    from jsonb_array_elements(coalesce(v_check.expected_staff,'[]'::jsonb)) s
    where s->>'id'=v_emp->>'id'
  ) then
    return jsonb_build_object('ok',false,'message','You are not on this month''s acknowledgement list. Please ask your manager.');
  end if;

  select acknowledged_at into v_ack
  from public.monthly_hs_acknowledgements
  where check_id=v_check.id
    and revision=v_check.revision
    and employee_id=v_emp->>'id'
  limit 1;

  return jsonb_build_object(
    'ok',true,
    'check_id',v_check.id,
    'site_id',v_check.site_id,
    'month_start',v_check.month_start,
    'revision',v_check.revision,
    'employee_id',v_emp->>'id',
    'employee_name',v_emp->>'name',
    'checks',v_check.checks,
    'manager_notes',v_check.manager_notes,
    'published_at',v_check.published_at,
    'acked',v_ack is not null,
    'acknowledged_at',v_ack
  );
end;
$$;

create or replace function public.monthly_hs_acknowledge(p_check_id uuid, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_check public.monthly_hs_checks%rowtype;
  v_emp jsonb;
  v_when timestamptz;
begin
  if p_pin is null or p_pin !~ '^\d{4}$' then
    return jsonb_build_object('ok',false,'message','PIN not recognised.');
  end if;

  select * into v_check
  from public.monthly_hs_checks
  where id=p_check_id
    and status='published'
    and month_start=date_trunc('month',current_date)::date
  limit 1;

  if not found then
    return jsonb_build_object('ok',false,'message','This monthly H&S check is not available.');
  end if;

  select e into v_emp
  from jsonb_array_elements(
    coalesce((select value->'employees' from public.shift_board where key='config'),'[]'::jsonb)
  ) e
  where coalesce((e->>'active')::boolean,true)
    and coalesce(e->>'siteId','')=v_check.site_id
    and coalesce(e->>'pin','')=p_pin
  limit 1;

  if v_emp is null then
    return jsonb_build_object('ok',false,'message','PIN not recognised for this site.');
  end if;

  if not exists (
    select 1
    from jsonb_array_elements(coalesce(v_check.expected_staff,'[]'::jsonb)) s
    where s->>'id'=v_emp->>'id'
  ) then
    return jsonb_build_object('ok',false,'message','You are not on this month''s acknowledgement list. Please ask your manager.');
  end if;

  insert into public.monthly_hs_acknowledgements(
    check_id,revision,site_id,month_start,employee_id,employee_name
  ) values (
    v_check.id,v_check.revision,v_check.site_id,v_check.month_start,v_emp->>'id',v_emp->>'name'
  )
  on conflict(check_id,revision,employee_id) do update
    set employee_name=excluded.employee_name
  returning acknowledged_at into v_when;

  if v_when is null then
    select acknowledged_at into v_when
    from public.monthly_hs_acknowledgements
    where check_id=v_check.id and revision=v_check.revision and employee_id=v_emp->>'id';
  end if;

  return jsonb_build_object(
    'ok',true,
    'employee_id',v_emp->>'id',
    'employee_name',v_emp->>'name',
    'acknowledged_at',v_when,
    'revision',v_check.revision
  );
end;
$$;

revoke all on function public.monthly_hs_kiosk_status(text) from public;
revoke all on function public.monthly_hs_for_pin(text,text) from public;
revoke all on function public.monthly_hs_acknowledge(uuid,text) from public;
grant execute on function public.monthly_hs_kiosk_status(text) to anon, authenticated;
grant execute on function public.monthly_hs_for_pin(text,text) to anon, authenticated;
grant execute on function public.monthly_hs_acknowledge(uuid,text) to anon, authenticated;
